### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by rechsteiner** [rechsteiner/Parchment#243]
Currently working on a larger release of Parchment that will include the following features:

- [x] **Remove the need for generics**  (#285)
Removing the generic type on PagingViewController will clean up the API quite a lot. The delegate and data sources are currently a bit awkward because of the generic types. You still need to force cast the type, so the benefit of using generic is mostly for the internal implementation.

- [x] **Remove FixedPagingViewController** (#304, #305)
One benefit of removing generics is that we can replace `FixedPagingViewController` with a `init(viewControllers:)` directly on `PagingViewController`.

- [x] **Allow menu to be used as a standalone component** (#379)
Having the menu as a separate component allows you to use it without having to use a `PageViewController` for your content. For instance, this allows you to use menu alongside a `UITableView` (like Fantastical), or use your own custom page view controller implementation.

- [x] **Add support for multiple cells types** (#390)
Without generics, we are no longer tied to a specific `PagingItem` type. This mean we can add support for registering different cell types for different `PagingItem` types. This would make it much cleaner to add buttons, loading indicators etc. to the menu collection view.

- [x] **Documentation**
Document breaking changes and create upgrade guide.

**Comment by TosinAF** [comment]
Hi @rechsteiner 

For 2.0, I found a bug whereas when there are two few paging items, there is no animation when changing pages. I dug in and found out it's because of 

`if collectionView.contentSize.width >= collectionView.bounds.width && state.progress != 0 {`

I was thinking of fixing by always having the content offset be .zero if the content size width is less than the width of the collection view.

What are your thoughts?

Cheers,
Tosin

**Comment by TosinAF** [comment]
<img width="721" alt="Screen Shot 2019-06-12 at 12 56 48 PM" src="https://user-images.githubusercontent.com/2206858/59381994-8eb99c00-8d11-11e9-923d-d44933c6e7b1.png">

**Comment by rechsteiner** [comment]
Hi @TosinAF! Thanks for the feedback. I've been a bit busy lately so I haven't had time to focus on the `2.0` refactor, but I'm planning on finishing it up soon. Need to look a bit more into your suggestion, bit it seems like that should work 🙂

**Comment by rechsteiner** [comment]
@TosinAF could you provide some more details on how I can reproduce this? I was looking into this now, but it seems to work fine for me.

**Comment by rechsteiner** [comment]
Version 2.0 is now available as a beta release 🥳

https://github.com/rechsteiner/Parchment/releases/tag/v2.0.0-beta

**Comment by rechsteiner** [comment]
Version 2.0 is now released! Let me know if you find any issues.
